services:
  # backend
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD="1681997"
    depends_on:
      - mysql

  # frontend service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Database service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD="1681997"
    ports:
      - "3306:3306"

    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes:
  mydata:


